# Generated by Django 5.1.3 on 2024-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0002_remove_recipeset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='rb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('address', models.TextField()),
            ],
        ),
    ]
