# Generated by Django 5.1.3 on 2024-11-29 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='time',
        ),
        migrations.AddField(
            model_name='item',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
