# Generated by Django 5.1.3 on 2024-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB', '0007_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
